#!/bin/sh

# On Fugaku platform only static build is supported(BUILD_SHARED_LIBS=Off)
# INTERACTIVE MODE

CXX=mpiFCC CC=mpifcc cmake -H. -Bbuild -DHIVE_BUILD_WITH_MPI=On -DHIVE_BUILD_WITH_PMLIB=Off -DHIVE_BUILD_WITH_CDMLIB=Off -DHIVE_BUILD_WITH_CPMLIB=Off -DHIVE_BUILD_WITH_BCMTOOLS=Off -DHIVE_BUILD_WITH_HDMLIB=Off -DHIVE_BUILD_WITH_PDMLIB=Off -DHIVE_BUILD_WITH_UDMLIB=Off -DHIVE_BUILD_WITH_COMPOSITOR=On -DHIVE_BUILD_WITH_OPENGL=Off -DHIVE_BUILD_WITH_NANOMSG=Off -DBUILD_SHARED_LIBS=Off -DHIVE_BUILD_WITH_OPENMP=On -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_C_FLAGS="-fPIC"
